name: notes_app
description: A clean, minimal notes and tasks app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Navigation
  go_router: ^17.0.0

  # Backend (Firebase)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_auth_web: ^6.1.0
  firebase_storage_web: ^3.11.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.2
  shared_preferences: ^2.5.3

  # UI & Media
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
